application: say-the-same-thing
version: 0-0-2
runtime: python27
api_version: 1
module: default
threadsafe: false

handlers:
- url: /favicon\.ico
  static_files: static/icons/favicon.ico
  upload: static/icons/favicon\.ico
- url: /static
  static_dir: static
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest